[package]
name = "relu-cuda-oxide"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]
members = ["kernels"]
default-members = ["."]

[lib]
crate-type = ["staticlib"]

[dependencies]
cuda-core = { git = "https://github.com/drbh/cuda-oxide.git", rev = "bc5f33bb1d556671c35e475439bb821d25caa2cb" }
tvm-ffi = { git = "https://github.com/apache/tvm-ffi.git", rev = "2af558e255ff2f398095835ae18e6457635b0262" }
