[general]
name = "relu-compiler-flags"
version = 1
license = "Apache-2.0"
backends = [
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-test/relu-compiler-flags"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.activation_xpu]
backend = "xpu"
depends = ["torch"]
sycl-flags = ["-DWHO_AM_I_IF_NOT_THE_CANARY"]
src = ["relu_xpu/relu.cpp"]

[kernel.activation]
backend = "cuda"
cuda-flags = ["-DWHO_AM_I_IF_NOT_THE_CANARY"]
depends = ["torch"]
src = ["relu_cuda/relu.cu"]

[kernel.activation_rocm]
backend = "rocm"
depends = ["torch"]
rocm-archs = [
    "gfx906",
    "gfx908",
    "gfx90a",
    "gfx940",
    "gfx941",
    "gfx942",
    "gfx1030",
    "gfx1100",
    "gfx1101",
]
hip-flags = ["-DWHO_AM_I_IF_NOT_THE_CANARY"]
src = ["relu_cuda/relu.cu"]
