[workspace]
members = [
    "kernel-abi-check",
    "kernel-builder",
    "kernels",
    "kernels-common",
]
resolver = "2"

[workspace.dependencies]
hf-hub = { version = "1.1.0", git = "https://github.com/huggingface/hf-hub", rev = "8b00e9eab4a27a614e414692d71791d8e33f7149", features = ["blocking"] }
