[general]
name = "relu-nki"
version = 1
license = "Apache-2.0"
backends = ["neuron"]

[general.hub]
repo-id = "kernels-test/relu-nki"

[general.neuron]
python-depends = ["nki"]

[torch-noarch]

[kernel]
