[package]
name = "relu-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
name = "relu_rust"

[dependencies]
# TODO: prefer using crate when published - pinning the release so moving to the crate should be frictionless.
tvm-ffi = { git = "https://github.com/apache/tvm-ffi.git", tag = "v0.1.14-post1" }
