[general]
name = "relu-tvm-ffi"
version = 1

backends = [
    "cpu",
    "cuda",
    "rocm",
    "xpu",
]

[tvm-ffi]
src = [
    "tvm-ffi-ext/tvm_ffi_binding.cpp",
]

[kernel.relu_cpu]
backend = "cpu"
src = ["relu_cpu/relu_cpu.cpp", "util.hh"]
depends = []

[kernel.relu_cuda]
backend = "cuda"
src = ["relu_cuda/relu.cu", "util.hh"]
depends = []

[kernel.relu_rocm]
backend = "rocm"
rocm-archs = [
    "gfx906",
    "gfx908",
    "gfx90a",
    "gfx940",
    "gfx941",
    "gfx942",
    "gfx1030",
    "gfx1100",
    "gfx1101",
]
src = ["relu_cuda/relu.cu", "util.hh"]
depends = []

[kernel.relu_xpu]
backend = "xpu"
src = ["relu_xpu/relu.cpp", "util.hh"]
depends = []
