[general]
name = "relu-tvm-ffi"
version = 1
edition = 6
license = "Apache-2.0"
backends = [
    "cpu",
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-test/relu-tvm-ffi"

[tvm-ffi]
src = ["tvm-ffi-ext/tvm_ffi_binding.cpp"]

[kernel.relu_cuda]
language = "cpp-cuda"
depends = []
src = [
    "relu_cuda/relu.cu",
    "util.hh",
]

[kernel.relu_rocm]
language = "cpp-rocm"
depends = []
src = [
    "relu_cuda/relu.cu",
    "util.hh",
]

[kernel.relu_cpu]
language = "cpp-cpu"
depends = []
src = [
    "relu_cpu/relu_cpu.cpp",
    "util.hh",
]

[kernel.relu_xpu]
language = "cpp-xpu"
depends = []
src = [
    "relu_xpu/relu.cpp",
    "util.hh",
]
