use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::path::Path;

use base64::prelude::{BASE64_STANDARD, Engine as _};
use digest::{Digest as _, DynDigest};
use eyre::{Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Sha256, Sha512};
use thiserror::Error;
use walkdir::WalkDir;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Digest {
    algorithm: DigestAlgorithm,
    files: BTreeMap<String, String>,
}

/// Digest violation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DigestViolation {
    /// A file in the reference digest is missing from the actual digest.
    MissingFile { path: String },

    /// A file present in the actual digest is not part of the reference digest.
    UnknownFile { path: String },

    /// The hashes for the file differ.
    HashMismatch {
        path: String,
        expected: String,
        got: String,
    },

    /// The digest algorithms differ.
    AlgorithmMismatch {
        expected: DigestAlgorithm,
        got: DigestAlgorithm,
    },
}

impl fmt::Display for DigestViolation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DigestViolation::MissingFile { path } => write!(f, "Missing file: {path}"),
            DigestViolation::UnknownFile { path } => write!(f, "Unknown file: {path}"),
            DigestViolation::HashMismatch {
                path,
                expected,
                got,
            } => write!(
                f,
                "File hash mismatch for {path}: expected: {expected}, got: {got}"
            ),
            DigestViolation::AlgorithmMismatch { expected, got } => write!(
                f,
                "Algorithm mismatch: expected: {expected:?}, got: {got:?}"
            ),
        }
    }
}

/// Error for digest mismatches.
#[derive(Clone, Debug, Eq, PartialEq, Error)]
#[error(
    "kernel does not match the expected digest:\n{}",
    .0.iter().map(ToString::to_string).collect::<Vec<_>>().join("\n")
)]
pub struct DigestError(Vec<DigestViolation>);

impl DigestError {
    /// Get the violations.
    ///
    /// This is never empty. Violations are ordered deterministically: files
    /// missing from or differing in the actual digest come first (ordered by
    /// path), followed by files only present in the actual digest.
    pub fn violations(&self) -> &[DigestViolation] {
        &self.0
    }
}

impl Digest {
    pub fn hash_variant(
        digest_algorithm: DigestAlgorithm,
        variant_path: impl AsRef<Path>,
    ) -> Result<Self> {
        let variant_path = variant_path.as_ref();

        let mut files = BTreeMap::new();
        for entry in WalkDir::new(variant_path) {
            let entry = entry.wrap_err("Failed to read directory entry for hashing")?;
            // Hub cache path can be symlinks.
            let path = fs::canonicalize(entry.path())?;
            if !path.is_file()
                // Metadata file hash cannot be computed, since it stores
                // hashes. It is protected by the detached signature.
                || (entry.depth() == 1
                    && entry.path().file_name().and_then(|f| f.to_str()) == Some("metadata.json"))
                || (entry.depth() == 1
                    && entry.path().file_name().and_then(|f| f.to_str())
                        == Some("metadata.json.sigstore"))
                // Exclude Python bytecode, these files are generated by the
                // interpreter since they are never included in builds or downloads.
                || entry.path().components().any(|c| c.as_os_str() == "__pycache__")
                || entry.path().extension().and_then(|e| e.to_str()) == Some("pyc")
            {
                continue;
            }

            let path = entry.path();

            // Read and hash contents.
            let contents = fs::read(path)
                .wrap_err_with(|| format!("Cannot read `{}` for hashing", path.display()))?;
            let mut hasher: Box<dyn DynDigest> = digest_algorithm.into();
            hasher.update(&contents);

            let relative_path = path.strip_prefix(variant_path).wrap_err_with(|| {
                format!("Cannot strip prefix from `{}` for hashing", path.display())
            })?;

            // Normalize Windows directory separators.
            let relative_path_str = relative_path.to_string_lossy().replace('\\', "/");

            let hash_base64 = BASE64_STANDARD.encode(hasher.finalize_reset());

            files.insert(relative_path_str, hash_base64);
        }

        Ok(Digest {
            files,
            algorithm: digest_algorithm,
        })
    }

    /// Algorithm used for hashing.
    pub fn algorithm(&self) -> DigestAlgorithm {
        self.algorithm
    }

    /// Validate a digest against the reference.
    ///
    /// Returns `Ok(())` if the two digests match. Otherwise returns a
    /// [`DigestError`] describing every way in which `other` deviates from
    /// `self`.
    pub fn validate(&self, other: &Self) -> Result<(), DigestError> {
        let mut violations = Vec::new();

        if self.algorithm != other.algorithm {
            violations.push(DigestViolation::AlgorithmMismatch {
                expected: self.algorithm,
                got: other.algorithm,
            });
        }

        for (path, expected) in &self.files {
            match other.files.get(path) {
                None => {
                    violations.push(DigestViolation::MissingFile { path: path.clone() });
                }
                Some(got) if got != expected => {
                    violations.push(DigestViolation::HashMismatch {
                        path: path.clone(),
                        expected: expected.clone(),
                        got: got.clone(),
                    });
                }
                Some(_) => {}
            }
        }

        for path in other.files.keys() {
            if !self.files.contains_key(path) {
                violations.push(DigestViolation::UnknownFile { path: path.clone() });
            }
        }

        if violations.is_empty() {
            Ok(())
        } else {
            Err(DigestError(violations))
        }
    }

    /// Mapping of relative path -> base64 digest.
    pub fn files(&self) -> &BTreeMap<String, String> {
        &self.files
    }
}

#[derive(Copy, Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
pub enum DigestAlgorithm {
    #[serde(rename = "sha256")]
    SHA256,

    #[serde(rename = "sha512")]
    SHA512,
}

#[cfg(test)]
mod tests {
    use super::*;
    use eyre::Result;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn hash_variant_hashes_file_with_sha256() -> Result<()> {
        let dir = TempDir::new()?;
        fs::write(dir.path().join("_extension.so"), b"hello world")?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        assert_eq!(digest.files().len(), 1);
        assert_eq!(
            digest.files().get("_extension.so").map(String::as_str),
            Some("uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek=")
        );
        Ok(())
    }

    #[test]
    fn hash_variant_hashes_file_with_sha512() -> Result<()> {
        let dir = TempDir::new()?;
        fs::write(dir.path().join("_extension.so"), b"hello world")?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA512, dir.path())?;

        assert_eq!(digest.files().len(), 1);
        assert_eq!(
            digest.files().get("_extension.so").map(String::as_str),
            Some(
                "MJ7MSJwS1utMxA9QyQLytNDtd+5RGnx6m808qG1M2G+YndNbxf9JlnDaNCVbRbDP2DDoH2Bdz33FVC6TrpzXbw=="
            )
        );
        Ok(())
    }

    #[test]
    fn hash_variant_skips_excluded_files() -> Result<()> {
        let dir = TempDir::new()?;
        let pycache_dir = dir.path().join("pkg").join("__pycache__");
        fs::create_dir_all(&pycache_dir)?;
        fs::write(dir.path().join("_extension.so"), b"content")?;
        fs::write(dir.path().join("metadata.json"), b"{}")?;
        fs::write(dir.path().join("metadata.json.sigstore"), b"sig")?;
        fs::write(pycache_dir.join("mod.cpython-311.pyc"), b"bytecode")?;
        fs::write(dir.path().join("payload.pyc"), b"smuggled")?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        assert_eq!(digest.files().len(), 1);
        assert!(digest.files().contains_key("_extension.so"));
        assert!(!digest.files().contains_key("payload.pyc"));
        assert!(!digest.files().contains_key("metadata.json"));
        assert!(!digest.files().contains_key("metadata.json.sigstore"));
        assert!(
            !digest
                .files()
                .contains_key("pkg/__pycache__/mod.cpython-311.pyc")
        );
        Ok(())
    }

    #[test]
    fn hash_variant_hashes_nested_metadata_json() -> Result<()> {
        let dir = TempDir::new()?;
        let subdir = dir.path().join("subdir");
        fs::create_dir_all(&subdir)?;

        // Top-level copies must be excluded.
        fs::write(dir.path().join("metadata.json"), b"{}")?;
        fs::write(dir.path().join("metadata.json.sigstore"), b"sig")?;

        // Nested copies must be included in the digest.
        fs::write(subdir.join("metadata.json"), b"{\"nested\": true}")?;
        fs::write(subdir.join("metadata.json.sigstore"), b"nested-sig")?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        // Top-level files are still excluded.
        assert!(!digest.files().contains_key("metadata.json"));
        assert!(!digest.files().contains_key("metadata.json.sigstore"));

        // Nested files must appear in the digest.
        assert!(
            digest.files().contains_key("subdir/metadata.json"),
            "subdir/metadata.json should be hashed but was excluded"
        );
        assert!(
            digest.files().contains_key("subdir/metadata.json.sigstore"),
            "subdir/metadata.json.sigstore should be hashed but was excluded"
        );

        Ok(())
    }

    #[test]
    fn hash_variant_uses_forward_slash_paths() -> Result<()> {
        let dir = TempDir::new()?;
        let subdir = dir.path().join("some").join("subdir");
        fs::create_dir_all(&subdir)?;
        fs::write(subdir.join("__init__.py"), b"data")?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        assert!(digest.files().contains_key("some/subdir/__init__.py"));
        Ok(())
    }

    #[test]
    fn hash_variant_returns_empty_map_for_empty_dir() -> Result<()> {
        let dir = TempDir::new()?;

        let digest = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        assert!(digest.files().is_empty());
        Ok(())
    }

    #[test]
    fn hash_variant_produces_deterministic_results() -> Result<()> {
        let dir = TempDir::new()?;
        fs::write(dir.path().join("_extension.so"), b"hello world")?;

        let digest1 = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;
        let digest2 = Digest::hash_variant(DigestAlgorithm::SHA256, dir.path())?;

        assert_eq!(digest1.files(), digest2.files());
        Ok(())
    }

    fn digest_with(files: &[(&str, &str)]) -> Digest {
        Digest {
            algorithm: DigestAlgorithm::SHA256,
            files: files
                .iter()
                .map(|(path, hash)| (path.to_string(), hash.to_string()))
                .collect(),
        }
    }

    #[test]
    fn validate_returns_no_violations_for_identical_digests() {
        let expected = digest_with(&[("a.so", "aaa"), ("b.py", "bbb")]);
        let actual = digest_with(&[("a.so", "aaa"), ("b.py", "bbb")]);

        assert_eq!(expected.validate(&actual), Ok(()));
    }

    #[test]
    fn validate_detects_missing_file() {
        let expected = digest_with(&[("a.so", "aaa"), ("b.py", "bbb")]);
        let actual = digest_with(&[("a.so", "aaa")]);

        assert_eq!(
            expected.validate(&actual),
            Err(DigestError(vec![DigestViolation::MissingFile {
                path: "b.py".to_string()
            }]))
        );
    }

    #[test]
    fn validate_detects_unknown_file() {
        let expected = digest_with(&[("a.so", "aaa")]);
        let actual = digest_with(&[("a.so", "aaa"), ("extra.so", "xxx")]);

        assert_eq!(
            expected.validate(&actual),
            Err(DigestError(vec![DigestViolation::UnknownFile {
                path: "extra.so".to_string()
            }]))
        );
    }

    #[test]
    fn validate_detects_hash_mismatch() {
        let expected = digest_with(&[("a.so", "aaa")]);
        let actual = digest_with(&[("a.so", "zzz")]);

        assert_eq!(
            expected.validate(&actual),
            Err(DigestError(vec![DigestViolation::HashMismatch {
                path: "a.so".to_string(),
                expected: "aaa".to_string(),
                got: "zzz".to_string(),
            }]))
        );
    }

    #[test]
    fn validate_collects_all_violations() {
        let expected = digest_with(&[("keep.so", "k"), ("gone.py", "g"), ("changed.so", "old")]);
        let actual = digest_with(&[("keep.so", "k"), ("changed.so", "new"), ("extra.bin", "e")]);

        // Violations are ordered: missing/mismatched files (in path order)
        // first, then files only present in the actual digest.
        assert_eq!(
            expected.validate(&actual),
            Err(DigestError(vec![
                DigestViolation::HashMismatch {
                    path: "changed.so".to_string(),
                    expected: "old".to_string(),
                    got: "new".to_string(),
                },
                DigestViolation::MissingFile {
                    path: "gone.py".to_string()
                },
                DigestViolation::UnknownFile {
                    path: "extra.bin".to_string()
                },
            ]))
        );
    }

    #[test]
    fn digest_error_exposes_violations_and_renders_all_messages() {
        let expected = digest_with(&[("gone.py", "g"), ("changed.so", "old")]);
        let actual = digest_with(&[("changed.so", "new"), ("extra.bin", "e")]);

        let err = expected.validate(&actual).unwrap_err();

        assert_eq!(err.violations().len(), 3);

        // Violations are rendered in their deterministic stored order.
        assert_eq!(
            err.to_string(),
            "kernel does not match the expected digest:\n\
             File hash mismatch for changed.so: expected: old, got: new\n\
             Missing file: gone.py\n\
             Unknown file: extra.bin"
        );
    }

    #[test]
    fn validate_detects_algorithm_mismatch_for_empty_digest() {
        let expected = Digest {
            algorithm: DigestAlgorithm::SHA256,
            files: BTreeMap::new(),
        };
        let actual = Digest {
            algorithm: DigestAlgorithm::SHA512,
            files: BTreeMap::new(),
        };

        assert_ne!(expected.algorithm(), actual.algorithm());

        let err = expected.validate(&actual).unwrap_err();

        assert_eq!(err.violations().len(), 1);
        assert_eq!(
            err.to_string(),
            "kernel does not match the expected digest:\n\
             Algorithm mismatch: expected: SHA256, got: SHA512"
        );
    }
}

impl From<DigestAlgorithm> for Box<dyn DynDigest> {
    fn from(digest_algorithm: DigestAlgorithm) -> Box<dyn DynDigest> {
        match digest_algorithm {
            DigestAlgorithm::SHA256 => Box::new(Sha256::new()),
            DigestAlgorithm::SHA512 => Box::new(Sha512::new()),
        }
    }
}
