"""
LayerNorm kernel generated by an AI agent using the triton-kernels skill.

This kernel was written following the patterns in:
    kernel-builder/skills/triton-kernels/SKILL.md

Demonstrates:
- Row-wise reduction (mean + variance)
- fp32 accumulation
- Masked loads with other=0.0
- Correctness test against torch.nn.functional.layer_norm
- Benchmark harness (GB/s)
"""

import torch
import triton
import triton.language as tl

DEVICE = torch.device(f'cuda:{torch.cuda.current_device()}')


@triton.jit
def layernorm_kernel(
    x_ptr, weight_ptr, bias_ptr, out_ptr,
    stride_row, D,
    eps: tl.constexpr,
    HAS_WEIGHT: tl.constexpr,
    HAS_BIAS: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    # One program per row (following SKILL.md reduction pattern)
    row = tl.program_id(0)
    offsets = tl.arange(0, BLOCK_D)
    mask = offsets < D

    # Load row into SRAM, accumulate in fp32 (SKILL.md: Hard Constraint #3)
    x = tl.load(x_ptr + row * stride_row + offsets, mask=mask, other=0.0).to(tl.float32)

    # Compute mean
    mean = tl.sum(x, axis=0) / D

    # Compute variance — zero out masked positions so they don't contribute
    x_centered = tl.where(mask, x - mean, 0.0)
    variance = tl.sum(x_centered * x_centered, axis=0) / D

    # Normalize
    inv_std = tl.rsqrt(variance + eps)
    x_norm = x_centered * inv_std

    # Apply affine transform if weight/bias exist
    if HAS_WEIGHT:
        w = tl.load(weight_ptr + offsets, mask=mask, other=1.0).to(tl.float32)
        x_norm = x_norm * w
    if HAS_BIAS:
        b = tl.load(bias_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
        x_norm = x_norm + b

    # Store back in input dtype (SKILL.md: cast back only at final store)
    tl.store(out_ptr + row * stride_row + offsets, x_norm, mask=mask)


def triton_layernorm(x, weight=None, bias=None, eps=1e-5):
    """LayerNorm wrapper following SKILL.md conventions."""
    # Hard Constraint #4: assert contiguous
    assert x.is_contiguous()

    x_2d = x.view(-1, x.shape[-1])
    out = torch.empty_like(x_2d)
    M, D = x_2d.shape

    has_weight = weight is not None
    has_bias = bias is not None
    if not has_weight:
        weight = torch.empty(0, device=x.device)
    if not has_bias:
        bias = torch.empty(0, device=x.device)

    # Hard Constraint #1: BLOCK_D covers full reduction dimension
    BLOCK_D = triton.next_power_of_2(D)
    # num_warps heuristic from SKILL.md
    num_warps = 4 if BLOCK_D <= 1024 else (8 if BLOCK_D <= 4096 else 16)

    layernorm_kernel[(M,)](
        x_2d, weight, bias, out,
        x_2d.stride(0), D, eps,
        has_weight, has_bias,
        BLOCK_D=BLOCK_D, num_warps=num_warps, num_stages=2,
    )
    return out.view_as(x)


# ============================================================
# Correctness test (SKILL.md: always validate before benchmarking)
# ============================================================

def test_layernorm():
    print("=" * 60)
    print("LayerNorm Correctness Tests")
    print("=" * 60)

    torch.manual_seed(0)
    test_cases = [
        ((1823, 781), "irregular shape"),
        ((1, 1), "single element"),
        ((4096, 4096), "large square"),
        ((32, 127), "small irregular"),
        ((2048, 2048), "power of 2"),
    ]

    # Test WITHOUT weight/bias
    print("\nWithout affine parameters:")
    for shape, desc in test_cases:
        x = torch.randn(shape, device=DEVICE, dtype=torch.float32)
        y_triton = triton_layernorm(x, eps=1e-5)
        y_ref = torch.nn.functional.layer_norm(x, [shape[-1]], eps=1e-5)
        try:
            torch.testing.assert_close(y_triton, y_ref, atol=1e-3, rtol=1e-3)
            print(f"  PASSED: {desc} {shape}")
        except AssertionError as e:
            print(f"  FAILED: {desc} {shape}: {e}")

    # Test WITH weight and bias
    print("\nWith affine parameters:")
    for shape, desc in test_cases:
        D = shape[-1]
        x = torch.randn(shape, device=DEVICE, dtype=torch.float32)
        weight = torch.randn(D, device=DEVICE, dtype=torch.float32)
        bias = torch.randn(D, device=DEVICE, dtype=torch.float32)
        y_triton = triton_layernorm(x, weight=weight, bias=bias, eps=1e-5)
        y_ref = torch.nn.functional.layer_norm(x, [D], weight=weight, bias=bias, eps=1e-5)
        try:
            torch.testing.assert_close(y_triton, y_ref, atol=1e-3, rtol=1e-3)
            print(f"  PASSED: {desc} {shape}")
        except AssertionError as e:
            print(f"  FAILED: {desc} {shape}: {e}")

    # Test bf16
    print("\nBFloat16:")
    x = torch.randn(1024, 1024, device=DEVICE, dtype=torch.bfloat16)
    weight = torch.randn(1024, device=DEVICE, dtype=torch.bfloat16)
    bias = torch.randn(1024, device=DEVICE, dtype=torch.bfloat16)
    y_triton = triton_layernorm(x, weight=weight, bias=bias, eps=1e-5)
    y_ref = torch.nn.functional.layer_norm(x, [1024], weight=weight, bias=bias, eps=1e-5)
    try:
        torch.testing.assert_close(y_triton, y_ref, atol=1e-2, rtol=1e-2)
        print(f"  PASSED: bf16 (1024, 1024)")
    except AssertionError as e:
        print(f"  FAILED: bf16: {e}")

    print()


# ============================================================
# Benchmark (SKILL.md: GB/s for memory-bound kernels)
# ============================================================

@triton.testing.perf_report(
    triton.testing.Benchmark(
        x_names=['N'],
        x_vals=[128 * i for i in range(2, 80)],
        line_arg='provider',
        line_vals=['triton', 'torch'],
        line_names=['Triton', 'PyTorch'],
        styles=[('blue', '-'), ('green', '-')],
        ylabel='GB/s',
        plot_name='layernorm-performance',
        args={'M': 4096},
    ))
def benchmark(M, N, provider):
    x = torch.randn(M, N, device=DEVICE, dtype=torch.float32)
    weight = torch.randn(N, device=DEVICE, dtype=torch.float32)
    bias = torch.randn(N, device=DEVICE, dtype=torch.float32)

    stream = torch.cuda.Stream()
    torch.cuda.set_stream(stream)

    if provider == 'torch':
        ms = triton.testing.do_bench(lambda: torch.nn.functional.layer_norm(x, [N], weight=weight, bias=bias))
    elif provider == 'triton':
        ms = triton.testing.do_bench(lambda: triton_layernorm(x, weight=weight, bias=bias))

    # Memory: read x + weight + bias, write output
    # Approximate as 2 * M * N (dominant terms)
    gbps = 2 * x.numel() * x.element_size() * 1e-9 / (ms * 1e-3)
    return gbps


if __name__ == "__main__":
    test_layernorm()

    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--benchmark":
        benchmark.run(save_path='.', print_data=True)
