//! Shared enumeration of the files that make up a kernel variant.

use std::fs;
use std::io;
use std::path::Path;

use walkdir::{DirEntry, WalkDir};

/// The files that make up a kernel variant, with their metadata.
///
/// Yields every regular file in `variant_path`, resolving symlinks: variants
/// in the Hub cache consist of symlinks into the blob store, so the symlink
/// target's metadata is the one that describes the variant's contents.
/// Symlinked directories are not descended into.
///
/// Python bytecode is skipped: it is generated by the interpreter and is
/// never part of a build or download.
///
/// Callers that need a narrower set filter the result further; in particular
/// `metadata.json` and `metadata.json.sigstore` *are* yielded.
pub(crate) fn variant_files(
    variant_path: &Path,
) -> impl Iterator<Item = io::Result<(DirEntry, fs::Metadata)>> {
    WalkDir::new(variant_path)
        .into_iter()
        .filter_entry(|entry| !is_python_bytecode(entry))
        .filter_map(|entry| {
            let entry = match entry {
                Ok(entry) => entry,
                Err(error) => return Some(Err(io_error(error))),
            };
            // Deliberately not `entry.file_type()`, which describes the
            // symlink rather than its target.
            match fs::metadata(entry.path()) {
                Ok(metadata) if metadata.is_file() => Some(Ok((entry, metadata))),
                Ok(_) => None,
                Err(error) => Some(Err(error)),
            }
        })
}

/// Python bytecode: a `.pyc` file, or a `__pycache__` directory to prune.
fn is_python_bytecode(entry: &DirEntry) -> bool {
    // Never filter out the variant directory itself, whose name is not part
    // of the variant.
    entry.depth() > 0
        && (entry.file_name() == "__pycache__"
            || entry.path().extension().and_then(|e| e.to_str()) == Some("pyc"))
}

/// Convert a [`walkdir::Error`], preserving the [`io::ErrorKind`] when the
/// underlying error is an I/O error rather than a symlink loop.
fn io_error(error: walkdir::Error) -> io::Error {
    let message = error.to_string();
    error
        .into_io_error()
        .unwrap_or_else(|| io::Error::other(message))
}
