#include <tvm/ffi/tvm_ffi.h>
#include <tvm/ffi/extra/c_env_api.h>

// Generated by TIRx codegen (tirx/relu.py); compiled into this extension.
extern "C" __global__ void relu_kernel(float* __restrict__ A_ptr, float* __restrict__ B_ptr,
                                       int n);

namespace {

constexpr int kThreads = 256;

void relu(tvm::ffi::TensorView input, tvm::ffi::TensorView out) {
  int64_t n = input.size(0);

  DLDevice device = input.device();
  cudaStream_t stream =
      static_cast<cudaStream_t>(TVMFFIEnvGetStream(device.device_type, device.device_id));

  dim3 grid((n + kThreads - 1) / kThreads);
  dim3 block(kThreads);
  relu_kernel<<<grid, block, 0, stream>>>(static_cast<float*>(input.data_ptr()),
                                          static_cast<float*>(out.data_ptr()),
                                          static_cast<int>(n));
  cudaError_t err = cudaGetLastError();
  if (err != cudaSuccess) {
    TVM_FFI_THROW(RuntimeError) << "relu launch failed: " << cudaGetErrorString(err);
  }
}

}  // namespace

TVM_FFI_DLL_EXPORT_TYPED_FUNC(relu, relu);
