[general]
name = "relu"
version = 1
license = "Apache-2.0"
backends = ["metal"]

[general.hub]
repo-id = "kernels-test/relu-metal-cpp"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.relu_metal]
backend = "metal"
depends = [
    "torch",
    "metal-cpp",
]
src = [
    "relu/relu.cpp",
    "relu/metallib_loader.mm",
    "relu/relu_cpp.metal",
    "relu/common.h",
]
