[general]
name = "kernel-deps"
version = 1
edition = 5
license = "apache-2.0"
backends = [
    "cpu",
    "cuda",
    "metal",
    "rocm",
    "xpu",
]

kernel-depends = [
    { repo-id = "kernels-staging/einops", revision = "pr1053" },
]

[general.hub]
repo-id = "kernels-test/kernel-deps"

[torch-noarch]

[kernel]
