[general]
name = "invalid-cpp-manylinux-symbols"
version = 1
license = "Apache-2.0"
backends = ["cpu"]

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.invalid_cpp_manylinux_symbols_cpu]
backend = "cpu"
depends = ["torch"]
src = ["cpu/cpu.cpp"]
