name: Build documentation

on:
  push:
    paths:
      - "docs/source/**"
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: kernels
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
