name: Lints
on:
  push:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUFF_VERSION: "0.15.10"
  GRIFFE_VERSION: "1.15.0"

jobs:
  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Run ruff check
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89  # v4.1.0
        with:
          src: kernels
          version: ${{ env.RUFF_VERSION }}
      - name: Run ruff format check
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89  # v4.1.0
        with:
          src: kernels
          version: ${{ env.RUFF_VERSION }}
          args: format --check

  griffe:
    name: Check API compatibility
    runs-on: ubuntu-latest
    env:
      UV_PYTHON_PREFERENCE: only-managed
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          python-version: "3.12"
      - name: Check for breaking changes
        run: uvx griffe==${{ env.GRIFFE_VERSION }} check kernels --search kernels/src -a main

  validate-dependencies:
    name: Validate python_depends.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Validate python_depends.json is up-to-date
        run: diff kernels-data/src/python_dependencies.json kernels/src/kernels/python_depends.json
